### ISSUE TITLE
Did you implement any order-independent transparency in the engine?

### ISSUE THREAD

**Issue by ldbfrank** [gan74/Yave#1]
Hi,
I am interesting in any OIT technology and wondering if you implement one of them in your engine?

Thanks.

**Comment by gan74** [comment]
No.

Yave isn't a game ready engine or anything, it's a pet project, mostly to learn Vulkan and engine design, it doesn't do anything more than the bare minimum of showing models on screen, if it even does that.

For now I am working on making a small editor for it so I can compose simple scenes. Once this done, I'll start to work on the rendering proper, but I haven't any plan for IOT. Stuff like shadows and GI will come first.
