### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [gan74/Yave#12]
.

**Comment by Dunk-Master** [comment]
If everyone is having build errors in the issues. You know the issue is not on my end. 
I wish you just gave the solution and everything on it

**Comment by Dunk-Master** [comment]
![image](https://github.com/gan74/Yave/assets/126705166/48fe3a12-2f9f-4e2f-b4b3-9ad9b88a4480)

**Comment by gan74** [comment]
Post the errors here then.
