### ISSUE TITLE
Cmake Build Error?

### ISSUE THREAD

**Issue by hynakim** [gan74/Yave#7]
I get that error when building in cmake
<img width="1280" alt="errorfil" src="https://user-images.githubusercontent.com/63955442/225303243-4877dea0-b766-44f8-b693-90e74b373305.png">

```
CMake Error at CMakeLists.txt:92 (add_subdirectory):
  The source directory

    C:/Users/dddd/Desktop/Yave/external/spirv_cross

  does not contain a CMakeLists.txt file.
```

**Comment by gan74** [comment]
You didn't clone the dependencies. The easiest way to do this is to use `git clone --recursive`

**Comment by iahung** [comment]
> You didn't clone the dependencies. The easiest way to do this is to use `git clone --recursive`

If he didn't clone the repo recursively, he can later use this command to clone the dependencies:

`git submodule update --init --recursive`
