### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by hynakim** [gan74/Yave#8]
sorry but i have another problem
When run it, the screen comes out black

<img width="1280" alt="errorfil" src="https://user-images.githubusercontent.com/63955442/225800989-ec84c169-389f-429f-a6af-306c3ea0aac7.png">
<img width="734" alt="errorfil2" src="https://user-images.githubusercontent.com/63955442/225801000-dd82521b-ffb2-4475-97a6-f6384446a5f6.png">

**Comment by gan74** [comment]
This is not an error, that what an empty scene looks like.

The errors in the console are expected, it can't find any asset or scene. These will go away if you import stuff.

**Comment by gan74** [comment]
Only gltf objects are supported.

Do you get any message in the console when loading an image ?

**Comment by hynakim** [comment]
If bring it up with engineview here, it will be forced to close.
<img width="1274" alt="errorfil3" src="https://user-images.githubusercontent.com/63955442/225853724-5ba86822-e18d-4e95-bfa6-d663705e7faa.png">

**Comment by gan74** [comment]
That's very wierd, the call stack seems to be in the scripting engine, which shouldn't even run here

**Comment by hynakim** [comment]
Built with visual studio code (vs2022)
Is this the wrong way?

**Comment by hynakim** [comment]
i haven't solved it yet
Are there any other solutions?

**Comment by hynakim** [comment]
Do you support Korean locale?

**Comment by hynakim** [comment]
Do you support Korean locale?

**Comment by hynakim** [comment]
Do you support Korean locale?
